- name: Copy kubeadm join command from master
  shell: kubeadm token create --print-join-command
  delegate_to: vm1_team2
  run_once: true
  register: kubeadm_join_cmd

- name: Join Kubernetes worker node
  command: "{{ kubeadm_join_cmd.stdout }}"
  when: inventory_hostname != 'vm1_team2'