# tasks/playbook_install_k8s_packages.yaml

- name: Remove old Kubernetes repository file
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: Remove old Kubernetes GPG key
  file:
    path: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    state: absent

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and dearmor Kubernetes GPG key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  args:
    executable: /bin/bash
    creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    filename: kubernetes.list
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold Kubernetes packages at current version
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: hold

- name: Enable and start kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started