apiVersion: batch/v1
kind: Job
metadata:
  name: consumer
spec:
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: 192.168.5.133:5000/consumer:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
      restartPolicy: Never

